const changenow_currencies = [
    {
        "ticker": "btc",
        "name": "Bitcoin",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "btc",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "btc"
    },
    {
        "ticker": "bch",
        "name": "Bitcoin Cash",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "bch",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "bch"
    },
    {
        "ticker": "ltc",
        "name": "Litecoin",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "ltc",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ltc"
    },
    {
        "ticker": "doge",
        "name": "Dogecoin",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "doge",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "doge"
    },
    {
        "ticker": "dash",
        "name": "Dash",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "dash",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "dash"
    },
    {
        "ticker": "trx",
        "name": "TRON",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "trx",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "trx"
    },
    {
        "ticker": "xrp",
        "name": "Ripple",
        "hasExternalId": true,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "xrp",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "xrp"
    },
    {
        "ticker": "xlm",
        "name": "Stellar",
        "hasExternalId": true,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "xlm",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "xlm"
    },
    {
        "ticker": "dot",
        "name": "Polkadot",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "dot",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "dot"
    },
    {
        "ticker": "algo",
        "name": "Algorand",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "algo",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "algo"
    },
    {
        "ticker": "xtz",
        "name": "Tezos",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "xtz",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "xtz"
    },
    {
        "ticker": "atom",
        "name": "Cosmos",
        "hasExternalId": true,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "atom",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "atom"
    },
    {
        "ticker": "fil",
        "name": "Filecoin",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "fil",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "fil"
    },
    {
        "ticker": "sol",
        "name": "Solana",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "sol",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "sol"
    },
    {
        "ticker": "apt",
        "name": "Aptos",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "apt",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "apt"
    },
    {
        "ticker": "ada",
        "name": "Cardano",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "ada",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ada"
    },
    {
        "ticker": "stx",
        "name": "Stacks",
        "hasExternalId": true,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "stx",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "stx"
    },
    {
        "ticker": "sui",
        "name": "Sui",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "sui",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "sui"
    },
    {
        "ticker": "tia",
        "name": "Celestia",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "tia",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "tia"
    },
    {
        "ticker": "iota",
        "name": "IOTA",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "iota",
        "tokenContract": null,
        "buy": false,
        "sell": false,
        "legacyTicker": "iota"
    },
    {
        "ticker": "hbar",
        "name": "Hedera Hashgraph",
        "hasExternalId": true,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "hbar",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "hbar"
    },
    {
        "ticker": "inj",
        "name": "Injective (Mainnet)",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "inj",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "injmainnet"
    },
    {
        "ticker": "near",
        "name": "NEAR Protocol",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "near",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "near"
    },
    {
        "ticker": "zec",
        "name": "Zcash",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "zec",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "zec"
    },
    {
        "ticker": "ton",
        "name": "Toncoin",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "ton",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ton"
    },
    {
        "ticker": "xmr",
        "name": "Monero",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "xmr",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "xmr"
    },
    {
        "ticker": "etc",
        "name": "Ethereum Classic",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "etc",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "etc"
    },
    {
        "ticker": "one",
        "name": "Harmony",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "one",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "one"
    },
    {
        "ticker": "celo",
        "name": "Celo",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "celo",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "celo"
    },
    {
        "ticker": "flr",
        "name": "Flare",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "flr",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "flr"
    },
    {
        "ticker": "xdc",
        "name": "XDC Network",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "xdc",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "xdc"
    },
    {
        "ticker": "matic",
        "name": "Polygon (Matic Mainnet)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "matic",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "maticmainnet"
    },
    {
        "ticker": "bnb",
        "name": "BNB Smart Chain",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "bsc",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "bnbbsc"
    },
    {
        "ticker": "sei",
        "name": "Sei",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "sei",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "sei"
    },
    {
        "ticker": "eth",
        "name": "Ethereum",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "eth",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "eth"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (Optimism)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "op",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ethop"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (Base)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "base",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ethbase"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (Arbitrum)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "arbitrum",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "etharb"
    },
    {
        "ticker": "cro",
        "name": "Cronos (EVM)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "croevm",
        "tokenContract": null,
        "buy": false,
        "sell": false,
        "legacyTicker": "croevm"
    },
    {
        "ticker": "kava",
        "name": "Kava",
        "hasExternalId": false,
        "isExtraIdSupported": true,
        "supportsFixedRate": true,
        "network": "kava",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "kava"
    },
    {
        "ticker": "avax",
        "name": "Avalanche (C-Chain)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "cchain",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "avaxc"
    },
    {
        "ticker": "mnt",
        "name": "Mantle",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "mnt",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "mntmainnet"
    },
    {
        "ticker": "pls",
        "name": "Pulsechain (PLS)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "pulse",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "pls"
    },
    {
        "ticker": "iotx",
        "name": "IoTeX",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "iotx",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "iotx"
    },
    {
        "ticker": "kaia",
        "name": "Kaia",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "kaia",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "kaia"
    },
    {
        "ticker": "s",
        "name": "Sonic (ex. FTM)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "sonic",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "s"
    },
    {
        "ticker": "bera",
        "name": "Berachain",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "bera",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "bera"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (Linea)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "lna",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "ethlna"
    },
    {
        "ticker": "bnb",
        "name": "opBNB (Optimistic Rollup)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "opbnb",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "opbnb"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (ZkSync Era)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "zksync",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "zksync"
    },
    {
        "ticker": "eth",
        "name": "Ethereum (Manta)",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": false,
        "network": "manta",
        "tokenContract": null,
        "buy": false,
        "sell": true,
        "legacyTicker": "ethmanta"
    },
    {
        "ticker": "egld",
        "name": "MultiversX",
        "hasExternalId": false,
        "isExtraIdSupported": false,
        "supportsFixedRate": true,
        "network": "egld",
        "tokenContract": null,
        "buy": true,
        "sell": true,
        "legacyTicker": "egld"
    },
]

/* missing: icp, arweave, thundercore */

export default changenow_currencies; 